# The directory containing the source files to parse recursively
source:
  - ../../pepabo.css-framework/project_sizucca/stylesheets/scss

# The directory that aigis will build to
dest: ../public_html

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./assets

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./template_jade
template_engine: jade
